version: '3.9'
x-spring-api-variables: &api-variables
  HOST: http://localhost:8080
  VERSION: v1.0
  PATH_BASE: /api
  PATH_MOVIES: /movies
  DB_HOST: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: reallystrongpassword
  HIBERNATE_DDL: update
  LIQUIBASE_CHANGE_LOGS: classpath:/db/changelog/db.changelog-master.xml
x-postgres-variables: &db-variables
  POSTGRES_DB: movie_hub_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: reallystrongpassword
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: *api-variables
    depends_on:
      - db

  db:
     image: postgres:15
     environment: *db-variables
     ports:
       - "5432:5432"