version: '3.9'
x-spring-ui-variables: &ui-variables
  API_HOST: http://localhost:8080
  API_VERSION: v1.0
  API_BASE_PATH: /api
  MOVIES_PATH: /movies
  DB_HOST: db
  DB_URL: jdbc:postgresql://db:5432/movie_hub_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: reallystrongpassword
  HIBERNATE_DDL: update
  LIQUIBASE_CHANGE_LOGS: classpath:/db/changelog/db.changelog-master.xml
x-postgres-variables: &db-variables
  POSTGRES_DB: movie_hub_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: reallystrongpassword
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment: *ui-variables
    depends_on:
      - db

  db:
     image: postgres:15
     environment: *db-variables
     ports:
       - "5432:5432"